clickhouse:
  target: local
  outputs:
    local:
      type: clickhouse
      schema: wiki
      host: localhost
      port: 8123
      user: clickhouserw
      password: clickhouserw_pass
      secure: False
    docker:
      type: clickhouse
      schema: wiki
      host: clickhouse
      port: 8123
      user: clickhouserw
      password: clickhouserw_pass
      secure: False
