clickhouse:
  target: local
  outputs:
    local:
      type: clickhouse
      schema: wiki
      host: localhost
      port: 8123
      user: user_666
      password: password_666
      secure: False
    docker:
      type: clickhouse
      schema: wiki
      host: clickhouse
      port: 8123
      user: user_666
      password: password_666
      secure: False
