version: "3"
services:
  wikissereader:
    image: wikissereader:latest
    environment:
      - URL=https://stream.wikimedia.org/v2/stream/recentchange
      - RABBIT_CONN_STR=amqp://rabbitrw:rabbitrw_pass@rabbit:5672
      - RABBIT_EXCHANGE=wikiexchange
    links:
      - rabbit
    depends_on:
      rabbit:
        condition: service_healthy
  rabbit:
    image: rabbitmq:3.12.12-management
    hostname: myrabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_NODENAME=myrabbit
    volumes:
      - ./conf_rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./conf_rabbit/definitions.json:/etc/rabbitmq/definitions.json
      - ./data_rabbit:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
  clickhouse:
    image: clickhouse/clickhouse-server:23.8.9.54
    ports:
      - "8123:8123"
    environment:
      - CLICKHOUSE_DB=wiki
      - CLICKHOUSE_USER=clickhouserw
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=clickhouserw_pass
    volumes:
    - ./conf_clickhouse/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    - ./conf_clickhouse/settings.xml:/etc/clickhouse-server/config.d/settings.xml
    - ./data_clickhouse:/var/lib/clickhouse/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    links:
      - rabbit
    depends_on:
      rabbit:
        condition: service_healthy
  wikidbt:
    image: wikidbt:latest
    links:
      - clickhouse
    depends_on:
      clickhouse:
        condition: service_healthy
  metabase:
    image: metabase/metabase:v0.48.5
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase.db
      - JAVA_TIMEZONE=UTC
    volumes:
      - ./conf_metabase/metabase.db:/metabase.db
      - ./conf_metabase/clickhouse.metabase-driver.jar:/plugins/clickhouse.metabase-driver.jar
    links:
      - clickhouse
    depends_on:
      clickhouse:
        condition: service_healthy
