version: "3.8"

services:
  wikidash:
    image: wikidash:latest
    networks:
      - internal
    environment:
      - CONN_STR=clickhouse://clickhousero:clickhousero_pass@clickhouse:9000/wiki
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=internal"
        # https://doc.traefik.io/traefik/middlewares/http/basicauth/#configuration-options
        - "traefik.http.middlewares.auth.basicauth.users=dezoomcamp:$$apr1$$X8u6Setv$$IuFYCvAx5sY1BU4FbmADb1"
        - "traefik.http.routers.wikidash.priority=1"
        - "traefik.http.routers.wikidash.rule=HostRegexp(`{name:.*}`)"
        - "traefik.http.routers.wikidash.service=wikidash"
        - "traefik.http.routers.wikidash.entrypoints=web"
        - "traefik.http.routers.wikidash.middlewares=auth"
        - "traefik.http.services.wikidash.loadbalancer.server.port=8000"

  traefik:
    image: traefik:v2.10.7
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.watch=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=internal"
      - "--entrypoints.web.address=:80"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

networks:
  internal:
    driver: overlay
    name: internal
    external: true
    attachable: true