
version: 2

sources:
  - name: wiki
    tables:
    - name: wiki

models:
  - name: wiki_hourly_summary
    description: "Number of events by hour"
    columns:
      - name: interval
        description: "Hourly interval for aggregation"
        tests:
          - unique
          - not_null
      - name: events
        description: "Number of events"
        tests:
          - not_null
      - name: update_time
        description: "Table update time"
        tests:
          - not_null
  - name: wiki_minutely_summary
    description: "Number of events by minute"
    columns:
      - name: interval
        description: "Minutely interval for aggregation"
        tests:
          - unique
          - not_null
      - name: events
        description: "Number of events"
        tests:
          - not_null
      - name: update_time
        description: "Table update time"
        tests:
          - not_null
